name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff

    - name: Rodar testes (pytest)
      run: pytest --maxfail=1 --disable-warnings -q

    - name: Verificar qualidade do código (ruff)
      run: ruff check .

    - name: Login no GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build da imagem Docker
      run: |
        docker build -t $REGISTRY/${IMAGE_NAME}:latest .

    - name: Push da imagem para o GHCR
      run: |
        docker push $REGISTRY/${IMAGE_NAME}:latest

    - name: Deploy no Kubernetes
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          kubernetes/deployment.yaml
          kubernetes/service.yaml
          kubernetes/configmap.yaml
          kubernetes/hpa.yaml
        images: |
          ghcr.io/${{ github.repository }}:latest
        kubectl-version: "latest"
        namespace: default
        kubeconfig: ${{ secrets.KUBECONFIG }}
